# Python CircleCI 2.0 configuration file
version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 pytest memelib
      # run flake8 and test
      - run:
          name: Lint Python
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
        - run:
            name: Run Tests
            command: |
            . venv/bin/activate
            pytest tests/test_meme.py